<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net8.0-windows</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UseWPF>true</UseWPF>
		<UseWindowsForms>true</UseWindowsForms>
		<ApplicationManifest>app.manifest</ApplicationManifest>
		<EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
		<CompilerGeneratedFilesOutputPath>$(BaseIntermediateOutputPath)\Generated</CompilerGeneratedFilesOutputPath>

	</PropertyGroup>

	<ItemGroup>
	  <None Remove="Resources\LabAssistant.ico" />
	  <None Remove="Resources\LabAssistant2.ico" />
	</ItemGroup>

	<ItemGroup>
		<Compile Update="Properties\Settings.Designer.cs">
		  <DesignTimeSharedInput>True</DesignTimeSharedInput>
		  <AutoGen>True</AutoGen>
		  <DependentUpon>Settings.settings</DependentUpon>
		</Compile>
		<Compile Update="Views\SwitchesPage.xaml.cs">
			<SubType>Code</SubType>
		</Compile>
	</ItemGroup>

	<ItemGroup>
	  <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
	  <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.7" />
	  <PackageReference Include="Microsoft.Xaml.Behaviors.Wpf" Version="1.1.135" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\LabAssistant.Business\LabAssistant.Business.csproj" />
	  <ProjectReference Include="..\LabAssistant.Models\LabAssistant.Models.csproj" />
	  <ProjectReference Include="..\LabAssistant.Services\LabAssistant.Services.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <Resource Include="Resources\LabAssistant.ico" />
	</ItemGroup>

	<ItemGroup>
	  <None Update="Properties\Settings.settings">
	    <Generator>SettingsSingleFileGenerator</Generator>
	    <LastGenOutput>Settings.Designer.cs</LastGenOutput>
	  </None>
	</ItemGroup>

</Project>
